// Generated by gencpp from file ford_msgs/ClusterHit.msg
// DO NOT EDIT!


#ifndef FORD_MSGS_MESSAGE_CLUSTERHIT_H
#define FORD_MSGS_MESSAGE_CLUSTERHIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ford_msgs
{
template <class ContainerAllocator>
struct ClusterHit_
{
  typedef ClusterHit_<ContainerAllocator> Type;

  ClusterHit_()
    : header()
    , ped_id(0)
    , likelihood(0.0)  {
    }
  ClusterHit_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ped_id(0)
    , likelihood(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _ped_id_type;
  _ped_id_type ped_id;

   typedef float _likelihood_type;
  _likelihood_type likelihood;





  typedef boost::shared_ptr< ::ford_msgs::ClusterHit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ford_msgs::ClusterHit_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterHit_

typedef ::ford_msgs::ClusterHit_<std::allocator<void> > ClusterHit;

typedef boost::shared_ptr< ::ford_msgs::ClusterHit > ClusterHitPtr;
typedef boost::shared_ptr< ::ford_msgs::ClusterHit const> ClusterHitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ford_msgs::ClusterHit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ford_msgs::ClusterHit_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ford_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ford_msgs': ['/home/wangqiang/catkin_ws/src/cadrl_ros_gazebo_demo/ford_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ford_msgs::ClusterHit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ford_msgs::ClusterHit_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ford_msgs::ClusterHit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ford_msgs::ClusterHit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ford_msgs::ClusterHit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ford_msgs::ClusterHit_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ford_msgs::ClusterHit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22a0a4f41b3e5b3041fdd6c1be6ae884";
  }

  static const char* value(const ::ford_msgs::ClusterHit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22a0a4f41b3e5b30ULL;
  static const uint64_t static_value2 = 0x41fdd6c1be6ae884ULL;
};

template<class ContainerAllocator>
struct DataType< ::ford_msgs::ClusterHit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ford_msgs/ClusterHit";
  }

  static const char* value(const ::ford_msgs::ClusterHit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ford_msgs::ClusterHit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 ped_id\n\
float32 likelihood\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ford_msgs::ClusterHit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ford_msgs::ClusterHit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ped_id);
      stream.next(m.likelihood);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterHit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ford_msgs::ClusterHit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ford_msgs::ClusterHit_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ped_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ped_id);
    s << indent << "likelihood: ";
    Printer<float>::stream(s, indent + "  ", v.likelihood);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORD_MSGS_MESSAGE_CLUSTERHIT_H
