(cl:defpackage ford_msgs-msg
  (:use )
  (:export
   "<CLUSTERHIT>"
   "CLUSTERHIT"
   "<CLUSTERS>"
   "CLUSTERS"
   "<IMAGEOBJ>"
   "IMAGEOBJ"
   "<IMAGERECT>"
   "IMAGERECT"
   "<NNACTIONS>"
   "NNACTIONS"
   "<PEDTRAJ>"
   "PEDTRAJ"
   "<PEDTRAJVEC>"
   "PEDTRAJVEC"
   "<PLANNERMODE>"
   "PLANNERMODE"
   "<POSE2DSTAMPED>"
   "POSE2DSTAMPED"
   "<SSDOBJS>"
   "SSDOBJS"
   "<PED_DETECTION>"
   "PED_DETECTION"
   "<POTENTIAL_DETECTIONS>"
   "POTENTIAL_DETECTIONS"
  ))

